HewlettPackard/X-TIME

- training/tests/estimators/test_catboost.py
- training/tests/estimators/test_lightgbm.py
- training/tests/estimators/test_xgboost.py
- training/xtime/contrib/unittest_ext.py
- training/xtime/estimators/estimator.py
NA
Unit tests associated with ML estimators now run in their own temporary working directories. No test artifacts are created and removed in the project directory tree.
> Improving execution of unit tests.

- training/tests/datasets/test_dataset.py
- training/xtime/datasets/dataset.py
- training/xtime/stages/search_hp.py
NA
Previously, the load method had totally different semantics compared to its save counterpart. This commit fixes it - the `save` method dumps datasets to disk, while the `load` method restores datasets from disk. The old method was used in one place, and its usage has been fixed.
> Unifying `Dataset` API.

- training/xtime/datasets/_rossmann_store_sales.py
#6 
In 2.0.0, only the first parameter can be positional, all others must be key-value paramters. This commit fixes it. No tests have been performed with pandas 2.0.0 though.
> Fixing the use of Pandas StringMethods.split method.

- training/tests/hparams/test_recommender.py
- training/xtime/hparams/_hparams.py
NA
This commit fixes one bug related to generating query in TinyDB format that is used to retrieve default hyperparameters for models and tasks. Search query (that is supposed to introduce constraints on model names and task types) was constructed using the wrong python API what was resulting in model type not being taken into account. This does not impact results published in the paper (since this implementation was added later, and back then default hyperparameters (which were exactly the same) were being retrieved using a different mechanism).
> Fix: invalid TinyDB query generation

- training/xtime/estimators/estimator.py
NA
This commit fixes a bug in the `MLflowCallback.after_test` callback method.
> BugFix: accessing metrics dictionary using invalid key.

- training/requirements.txt
NA
Ray tune conflicts with latest pydantic (project indirect dependency) versions. Version that needs to be installed < 2.
> Adding pydantic version constraint to requirements file.

- training/xtime/datasets/dataset.py
NA
The `build_dataset` function now checks if requested dataset is present in the dataset registry before attempting to create it. If not, exception is raised with the human-friendly message.
> Checking if dataset is available before trying to create it.

- training/xtime/datasets/_wisdm.py
NA
The `tsfresh` import can fail, and this may occur because `tsfresh` depends on `stumpy` that depends on `numba` that detects CUDA runtime and tries to use it if available.  The message suggests to disable CUDA for numba by exporting NUMBA_DISABLE_CUDA environment variable (https://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_DISABLE_CUDA): `export NUMBA_DISABLE_CUDA=1`.
> Extended message when `tsfresh` import fails.

- training/tests/contrib/test_tune_ext.py
- training/tests/hparams/test_recommender.py
- training/tests/test_cli.py
- training/xtime/contrib/tune_ext.py
- training/xtime/estimators/estimator.py
- training/xtime/hparams/__init__.py
- training/xtime/hparams/_hparams.py
- training/xtime/io.py
- training/xtime/main.py
- training/xtime/stages/search_hp.py
- training/xtime/stages/train.py
NA
This commit introduces better support of hyperparameters and fixes several bugs related to them.
1. Hyperparameters specified with Ray Tune can now be serialized in YAML files.
2. Train and HP search commands do not fail now when errors occurred on writing various files (dataset info and run inputs).
3. Unifying access to HP from systems such as hyperparameter recommenders. To get default hyperparameters or their search spaces, or get recommendations, the following format is used: 
```
--params='auto:default:model=xgboost;task=binary_classification;run_type=train' 
```
This example asks `default` recommender to get HPs for XGBoost model solving binary classification problem. Run type is set to `train` instructing to return HP values and not HP search spaces.
> Better hyperparameter support

- training/xtime/datasets/_ozone_level_detection_one_hour.py
NA
Removing column label from the list of features in dataset metadata (`ozone_level_detection_1hr` dataset).
> Fixing OZON dataset (label in feature list)

- training/tests/datasets/test_preprocessing.py
NA
Replacing `assertEquals` with `assertEqual` in `test_preprocessing.py`.
> Replacing deprecated calls assertEquals.

- training/xtime/estimators/_xgboost.py
NA
Removing `early_stopping_rounds` parameter from the `fit` method and moving it to `set_params` as recommended by XGBoost library.
> Fixing XGBoost warning related to use of `early_stopping_rounds` parameter.

- training/tests/datasets/test_dataset.py
- training/tests/estimators/test_catboost.py
- training/tests/estimators/test_lightgbm.py
- training/tests/estimators/test_xgboost.py
- training/tests/test_cli.py
- training/tests/test_registry.py
- training/xtime/contrib/mlflow_ext.py
- training/xtime/datasets/__init__.py
- training/xtime/datasets/dataset.py
- training/xtime/estimators/estimator.py
- training/xtime/main.py
- training/xtime/stages/search_hp.py
- training/xtime/stages/train.py
NA
This commit adds support for external datasets. External datasets are serialized instances of the `Dataset` class. CLI interface that accepts dataset names in the form `name:version` can now accept paths to directories storing these serialized datasets.
Several new classes are added to support this feature. Some of existing methids in `datasets` module has been moved to some other places. New classes that support the new feature:
- `DatasetFactory`: base class for all factories that create datasets.
- `SerializedDatasetFactory`: factory that creates serialized datasets.
- `RegisteredDatasetFactory`: factory that creates registerted (standard) datasets.
> Support for external datasets.

- training/xtime/estimators/estimator.py
NA
This commit adds R2 (coefficient of determination) scores for regression tasks. This includes out-of-sample (OOS) R2-score. The OOS R2 score is computed as `1.0 - model_mse / benchmark_model_mse`, where benchmark model is the regressor that predicts mean of the train set.
> Adding R2 scores.

- training/xtime/errors.py
- training/xtime/main.py
- training/xtime/registry.py
NA
This commit modifies the class registry class so that it does not fail when a module cannot be imported (`ImportError` error). This can be the case when a module's dependencies have not been installed (such as, for instance, `LightGBM` library for the `LightGBMClassifierEstimator` model).
> ClassRegistry to support modules that cannot be imported.

- training/README.md
- training/poetry.lock
- training/pyproject.toml
NA
This commit makes some of dependencies that were listed in their own groups to be extra dependencies of this project.
- These dependencies are - `catboost`, `xgboost`, `lightgbm` and `tsfresh`.
- They were moved to the `main` groups and were made optional.
- New section in `pyproject.toml` that declares extra dependencies - `catboost`, `xgboost`, `lightgbm` and `timeseries`.
These changes result in a fact that these libraries are not installed by default anymore.
- To install all extra dependencies (needed for development): `poetry install --all-extras`.
- To install only certain dependencies: `poetry install --extras "catboost timeseries"`.
These extra dependencies will also be possible to install with `pip`.
> Updating project dependencies.

- training/README.md
- training/pyproject.toml
- training/xtime/datasets/_eye_movements.py
- training/xtime/datasets/_gas_concentrations.py
- training/xtime/datasets/_gesture_phase.py
- training/xtime/datasets/dataset.py
NA
XIME depends on `openml` library to download datasets hosted on OpenML site. This dependency is optional now, install it with `--extras openml`. The presence of this library is checked in `_check_pre_requisites` methods. To implement this, a new class is added - DatasetPrerequisites - that will provide standard checks for dataset prerequisites.
> Making `openml` extra dependency.

- training/README.md
- training/pyproject.toml
NA
Adding new groups of (meta) dependencies that install:
- `datasets`: Install packages to ensure all datasets can be loaded (includes [`openml`, `timeseries`]).
- `models`: Install packages to ensure all models can be loaded (includes [`catboost`, `xgboost`, `lightgbm`]).
- `all`: Install all extra packages.
> New extra (meta)  dependencies.

- training/poetry.lock
- training/pyproject.toml
NA
Fixing typo in project name (in `pyproject.toml`): `extime-training` -> `xtime-training`.
> Fixing typo in project name.

- training/xtime/contrib/tune_ext.py
- training/xtime/stages/search_hp.py
NA
A dataset that contains train and valid splits and that does not contain a test split causes errors in several places. This commit fixes by checking what metrics are present, and logging (summarizing) only those that present.
> Correct processing of `missing metric` case.

- training/xtime/estimators/_xgboost.py
NA
Transitioning from `{"gpu_id": 0, "tree_method": "gpu_hist"}` to `{"device": "cuda", "tree_method": "hist"}` XGBoost estimator parameters when `--gpu` flag is present.
> New XGBoost GPU device specification.

- training/README.md
- training/xtime/main.py
- training/xtime/stages/search_hp.py
NA
This commit changes the meaning of the `--gpu` command line argument parameter. In current implementation, it is a flag. When set, the Ray Tune scheduler assigns one trial to one GPU. This commit changes it to be an option with value being a GPU fraction - numerical value between 0 and 1 - that defines how much GPU a trial can potentially consume.
- When not provided, no GPUs will be used.
- When no value provided (`--gpu`), the value is set to 1 (this is backward compatible with current implementation).
- In all other cases, Ray Tune will use this value for scheduling multiple trials in parallel on a single GPU. For instance, with `--gpu 0.1` ten parallel trials can be scheduled on each GPU.
> Adding support for multiple parallel trials to use one GPU.

- training/xtime/errors.py
- training/xtime/estimators/_catboost.py
- training/xtime/estimators/_lightgbm.py
- training/xtime/estimators/_sklearn.py
- training/xtime/estimators/_xgboost.py
NA
The xtime estimators (xgboost, lightgbm, catboost and sklearn) now check if validation split is present. If it is present, they use it as eval set. No exceptions are raised when datasets do not provide validation splits.
> Making validation sets optional for estimators.

- training/tests/datasets/test_churn_modelling.py
- training/tests/datasets/test_eye_movements.py
- training/tests/datasets/test_forest_cover_type.py
- training/tests/datasets/test_gas_concentrations.py
- training/tests/datasets/test_gesture_phase.py
- training/tests/datasets/test_rossmann_store_sales.py
- training/tests/datasets/test_telco_customer_churn.py
- training/tests/datasets/test_year_prediction_msd.py
- training/xtime/datasets/_churn_modelling.py
- training/xtime/datasets/_eye_movements.py
- training/xtime/datasets/_forest_cover_type.py
- training/xtime/datasets/_gas_concentrations.py
- training/xtime/datasets/_gesture_phase.py
- training/xtime/datasets/_rossmann_store_sales.py
- training/xtime/datasets/_telco_customer_churn.py
- training/xtime/datasets/_year_prediction_msd.py
- training/xtime/datasets/dataset.py
NA
This commit adds support from single-precision (float32) datasets. New dataset version (`numerical32`) is added. This is essentially the same as numerical, except that column types are converted to `np.float32` data type.
> Support for single-precision datasets.

- training/xtime/datasets/_churn_modelling.py
- training/xtime/datasets/_eye_movements.py
- training/xtime/datasets/_forest_cover_type.py
- training/xtime/datasets/_gas_concentrations.py
- training/xtime/datasets/_gesture_phase.py
- training/xtime/datasets/_telco_customer_churn.py
- training/xtime/datasets/dataset.py
NA
For classification datasets that already have unit tests, the type of label series is changed from default (int64) to int32 (that is expected by most ML libraries). For datasets that do not have unit tests yet, this needs to be done in future commits.
> Changing label types from int64 to int32.

- training/tests/hparams/test_hparams.py
- training/xtime/hparams/_hparams.py
NA
Two bugs are fixed in this commit:
- Empty parameter specs are ignored. This is caused by adding one or several `;` at the end of the specification string, e.g., "params:;n_streams=4;n_estimators=1;n_trees=1;".
- Raising an error if parased parameter name is not a valid python identifier. This can happen when accidently a parameter is placed in front on the protocol spec, e.g., "n_streams=4;params:n_estimators=1;n_trees=1;". In this case, parameter name "params:n_estimators" is not a valid identifier.
> Fixing bugs in parsing hparams.

- training/xtime/stages/search_hp.py
NA
This commit makes ray dashboards listen on all available interfaces (0.0.0.0) so that they are accesible from remote machines. This applies to hyperparameter search runs (`search_hp`).
> Ray dashboards listen on all available interfaces (0.0.0.0).

- training/README.md
- training/xtime/estimators/estimator.py
- training/xtime/stages/search_hp.py
NA
Users can now set `XTIME_SEARCH_HP_PRE_LOAD_DATASET` environment variable to 1 to instruct the `search_hp` stage to load the dataset in advance and distribute it to worker processes via ray object store.
> Pre-loading dataset for hyperparameter search.

- training/xtime/errors.py
- training/xtime/estimators/_catboost.py
- training/xtime/estimators/_lightgbm.py
- training/xtime/estimators/_rapids.py
- training/xtime/estimators/_xgboost.py
NA
Starting from this commit, all estimator implementations raise the `EstimatorError` error (with the help of `library_not_installed` class method) informing that an estimator is not available due to missing optional dependencies. The XTIME prints out this information at a warning level.
> `Library not installed` warning message for estimators.

- training/poetry.lock
- training/pyproject.toml
NA
Older version of Ray that this project uses (`2.3.1` for python < `3.11`) are not compatible with the latest versions of the `setuptools` package (`ImportError: cannot import name 'packaging' from 'pkg_resources'`). The solution described [here](https://stackoverflow.com/questions/78604018/importerror-cannot-import-name-packaging-from-pkg-resources-when-trying-to)  is to use earlier version (s). This commit introduces a constraint for the `setuptools` package for python versions < `3.11` where there's a conflict with Ray.
> Setuptools version constraints for python < 3.11.

- .gitignore
- training/pyproject.toml
- training/tests/test_version.py
- training/xtime/__init__.py
NA
This commit adds dynamic versioning feature for the `training` project. It is based on dynamic versioning plugin for Poetry (https://github.com/mtkennerly/poetry-dynamic-versioning). To install it, run:
```bash
poetry self add "poetry-dynamic-versioning[plugin]"
poetry version
```
- A new `xtime.__version__` variable is added that is computed on the fly:
- First, try poetry dynamic versioning pluging to determine the project version. Useful for development.
- Then, try project metadata. Works when package is installed.
- In addition, a new file `xtime/_version.py` is generated (that becomes part of binary and source distributions) that is tested.
- The `poetry build` command produces versioned wheel and source distribution.
- Nox tests work too.
- This plugin relies on Git tags. The …
> Dynamic versioning for the training project.

- training/noxfile.py
- training/pyproject.toml
NA
Setting back project version in `pyproject.toml` to its placeholder value - `0.0.0` (actual version is computed by the poetry dynamic versioning plugin on the fly).
- Adding description in `pyproject.toml` explaining this is a placeholder version.
- Adding `nox` test to check the value of the version parameter.
> Resetting project version in pyproject.toml.

- training/README.md
- training/poetry.lock
- training/pyproject.toml
- training/xtime/estimators/_rapids.py
NA
For the upcoming support for Python 3.12, this commit removes cuML libraries from `pyproject.toml`. Instead, when users request these models, they will see a warning message with instructions on how to manually install these libraries.
This is (probably) a temporary solution for now. We need to figure out how to resolve some of the conflicts in package versions when python 3.12 is listed as a supported runtime.
> Transitioning cuML random forest models from extras to manual installation

- training/noxfile.py
NA
This commit adds `pytest-xdist` dependency for nox-based tests to run unit tests in parallel (within one session). Enable it with `-n NUM_PROCESSES` CLI argument, for example:
```bash
nox -s "unit-3.11(deps='latest')" -- -n 14
```
to run 14 parallel tests.
> Enabling parallel unit tests with nox.

- training/xtime/io.py
NA
This commit adds optional parameter (`expected_keys`) to `IO.load_dict` method. If not None, the method will ensure that the loaded dictionary contains these keys.
> Optional validation that loaded dictionaries contain expected keys.

- training/noxfile.py
NA
This commit adds a new test session that invokes xtime's train stage and then validates its outputs. Three models can be used with this test - `xgboost`, `catboost` and `lighgbm`:
```bash
nox -l
nox -s "model_train_test(model='xgboost')"
nox -s "model_train_test(model='catboost')"
nox -s "model_train_test(model='lightgbm')"
```
> Nox test for the train stage.

- training/xtime/stages/search_hp.py
NA
Nox tests run in isolated python environments, and file system paths to these environments maybe quite long. Nox sessions have their own temp directories that are located inside python environments. Ray raises the following error "OSError: AF_UNIX path length cannot exceed 107 bytes". This commit fixes it by introducing an environment variable that is set in NOX environments. In this case, the `search_hp` stage instructs to use the host `/tmp/ray` as ray's temporary directory.
> Updating `search_hp` stage to "support" NOX tests.

- training/xtime/contrib/mlflow_ext.py
NA
This commit adds new method parameter - `raise_if_not_exist (bool)`. If MLflow run's artifact path does not exist (not a directory), the method raises the `FileNotFoundError` error.
> Validate path exists in MLflow.get_artifact_path method.

- training/noxfile.py
- training/poetry.lock
- training/pyproject.toml
- training/xtime/contrib/mlflow_ext.py
- training/xtime/contrib/tune_ext.py
- training/xtime/estimators/estimator.py
- training/xtime/stages/search_hp.py
NA
This commit adds support for python 3.12. Concretely:
- The `pyproject.toml` declares 3.12 as supported runtime. New package dependencies are introduced for python 3.12. New `poetry.lock` is commited too.
- New nox tests are added that test `train` and `search_hp` stages for the following models - `xgboost`, `catboost` and `lightgbm`. For complete list of tests, run `nox -l`.
- Several code changes are introduced to support newer versions of packages that break their previous API:
- Better support for environment variables in MLflow.
- Changes in Ray Tune API (related to `log_dir` and `path` of trials and results).
One update needs further investigation. For some reason, probably due to how ray's object store deals with numpy arrays (used by Pandas data frames), the latest LightGBM …
> Python 3.12 support

- .pre-commit-config.yaml
- training/xtime/run.py
NA
This commit adds pre-commit hooks for the training subproject. Also, one warning is silenced. This needs a fix in the future (search for `FIXME`).
NA
> Adding pre-commit hooks for the training subproject.

- training/xtime/errors.py
- training/xtime/estimators/estimator.py
NA
This commit adds a new performance metric - precision recall (PR) curve. It works for binary classification models. It is serialized as two files:
- Yaml file containing precision, recall and threshold arrays that were used to build the PR curve.
- Image (png) file that is graphical representation of the curve with threshold-recall curve on the same chart. The function that computes PR curve is decorated with a function decorator that ignores any exceptions raised during the process of computing the curve. This decorator (ignore_exceptions) is also part of this commit and can be used for other functions too.
Select all that apply, and delete the others. If these changes are for `xtime.training`, please make sure to
provide unit tests and/or nox tests for bug fixes and new features.
> Precision recall curve metric for binary classifiers.

- training/tests/contrib/test_mlflow_ext.py
- training/xtime/contrib/mlflow_ext.py
- training/xtime/stages/search_hp.py
- training/xtime/stages/train.py
NA
Users can configure MLflow run names using `MLFLOW_RUN_NAME` environment variable. This is supported in `search_hp` and `train` stages.
Select one of these options, and delete the others.
Select all that apply, and delete the others. If these changes are for `xtime.training`, please make sure to
provide unit tests and/or nox tests for bug fixes and new features.
> Configure MLflow run name.

- training/xtime/io.py
Two logging calls - warning and debug, with debug call printing the same information.
> Removing redundant logging call.

- training/poetry.lock
- training/pyproject.toml
NA
This is to fix seeing VSCode warning message about deprecated `ruff-lsp` server.
- NA
> Bumping ruff version to 0.9.10.

- training/tests/hparams/test_hparams.py
- training/xtime/hparams/_hparams.py
NA
- Fixing several bugs (such as not being able to load hyperparameters from files when they have `file:` protocol specification).
- Previously, hyperparameters loaded from files were used as is. No, it is assumed that loaded dictionary of hyperparameters is flat, and string values are evaluated using Python's `eval` function. Now, it is possible to specify things such as `ValueSpec` in files as string values. This may have unexpected effects though (such as converting string "5" to integer 5).
- Refactoring existing and adding new unit tests.
> Fixing bugs and improving hyperparameter handling.
