HewlettPackard/X-TIME

- LICENSE
- README.md
Add LICENSE file and update README.md.
> Adding information about License (Apache 2.0).

- .github/pull_request_template.md
Initial version of the template for new pull requests.
> Adding pull request template.

- training/README.md
None.
In one example command that shows how to install additional dependencies from requirements file the `-r` was missing.
> Fixing typo in training README file.

- training/xtime/contrib/mlflow_ext.py
NA
- Adding doc strings.
- Fixing bug related to use of older API (`list_experiments`) that does not exist in new versions. Changed to `search_experiments`.
- Fixing bug related to page_token not being used when invoking mlflow's `search_run` function.
> Updating MLflow class that simplifies interaction with MLflow.

- training/xtime/estimators/estimator.py
NA
Adding the following metrics: ROC_AUC, F1, precision and recall scores.
> New ML metrics for binary classification problems.

- training/xtime/contrib/mlflow_ext.py
NA
The goal is to be able to log arbitrary dictionaries of metrics ignoring those that cannot be logged by MLflow (e.g., invalid value types).
> Adding method to safely log ML metrics with MLflow.

- training/tests/stages/test_search_hp.py
- training/xtime/stages/search_hp.py
NA
- Refactoring a function that returns metrics for the best trial: new name that better communicates what this function does and now this function returns all metrics not performing any filtering.
- Logging this extended set of metrics with MLflow and in separate file.
> Logging new metrics with MLflow for hyperparameter search experiments.

- training/poetry.lock
- training/pyproject.toml
- training/tests/test_registry.py
- training/xtime/datasets/_wisdm.py
NA
WISDM is a WIreless Sensor Data Mining dataset hosted on this site: https://www.cis.fordham.edu/wisdm/dataset.php. The goal of adding this dataset is to demonstrate the use of tree-based models for timeseries related problems. In this particular case, it's a multi-variate timeseries classification.
> Adding WISDM dataset.

- training/README.md
NA
Adding a section in README file that describes supported environment variables.
> Documenting supported environment variables.

- training/xtime/datasets/_churn_modelling.py
- training/xtime/datasets/_rossmann_store_sales.py
- training/xtime/datasets/_telco_customer_churn.py
- training/xtime/datasets/_wisdm.py
- training/xtime/datasets/dataset.py
NA
This commit adds a method in `DatasetBuilder` class to check for dataset pre-requisites before building any version of a dataset. Examples are - availability of optional dependencies, dataset files if they need to be downloaded manually, etc. All checks that existed in `__init__` methods are moved to this new method in this commit. This also means that all dataset `__init__` methods do not raise exceptions, and commands such as `dataset list` will work even when dataset pre-requisites are not met.
> Adding dataset pre-requisites.

- training/poetry.lock
- training/pyproject.toml
- training/xtime/datasets/_wisdm.py
- training/xtime/datasets/_year_prediction_msd.py
- training/xtime/datasets/dataset.py
- training/xtime/io.py
- training/xtime/main.py
NA
- Adding global cli parameter `--log-level` (e.g., python -m xtime.main --log-level=debug ...) so that users can control amount of information being printed on their consoles.
- Replacing all print statememts with logging debug calls.
- By default, printing human-friendly messages when commands fail. Rerunning with --log-level=debug argument will output detailed information about errors.
- When CLI commands faile, exiting with `1` status code.
- Adding new dependency (`coloredlogs`).
> Adding logging feature for the project.

- training/xtime/stages/search_hp.py
NA
In current implementation, concurrency limits are not propagated to basic variant generator (random) search algorithm. This commit fixes it:
- By default, there's no limit.
- HyperOpt search algorithm is limited to use 2 parallel trials.
> Fixing concurrency limiter bug.

- training/tests/datasets/test_preprocessing.py
- training/tests/test_cli.py
- training/xtime/datasets/_wisdm.py
- training/xtime/datasets/preprocessing.py
NA
This commit adds several components that can be used in timeseries datasets.
- `TimeSeries` class can be used to apply the sliding window transform to a time series.
- `TimeSeriesEncoderV1` class can be used to convert time series segments into features suitable for ML models.
> Common processing for timeseries data.

- training/xtime/datasets/_ozone_level_detection_one_hour.py
NA
Adding new `Ozone Level Detection` dataset  hosted by UC Irvine ML repository (https://archive.ics.uci.edu/dataset/172/ozone+level+detection).
> New dataset (Ozone Level Detection)

- training/tests/test_registry.py
NA
Fixing test registry unit test by adding a dataset (`ozone_level_detection_1hr`) check that was added previously.
> Fixing unit test bug (missing dataset).

- training/tests/test_registry.py
- training/xtime/datasets/_fraud_detection.py
NA
Adding new Fraud Detection ([kaggle](https://www.kaggle.com/datasets/volodymyrgavrysh/fraud-detection-bank-dataset-20k-records-binary?resource=download)) dataset (binary classification). Expected performance metrics (accuracy):
- Dataset: `fraud_detection:default`.
- Baseline: train (73.27), test (74.08).
- XGBoost: train (98.84), test (94.24).
> Adding Fraud Detection (fraud_detection) dataset.

- training/xtime/datasets/_fraud_detection.py
NA
Adding missing imports in fraud detection dataset. Also, fixing some warnings for this dataset.
> Fixing missing import (`DatasetError`) in fraud detection dataset.

- training/tests/test_registry.py
- training/xtime/datasets/_harth.py
Adding new HARTH ([UC Irvine ML repository](https://archive.ics.uci.edu/dataset/779/harth)) dataset (multi-class classification). Expected performance metrics (accuracy):
- Dataset: `harth:default`.
- Baseline: train (53.36), test (3.91).
- XGBoost: train (99.69), test (86.71).
> Adding Human Activity Recognition Trondheim (HARTH) dataset.

- training/xtime/datasets/_wisdm.py
List all related issues and/or pull requests if there are any.
Include a brief summary of the proposed changes.
> added copyright license

- training/tests/datasets/test_dataset.py
- training/xtime/datasets/_fraud_detection.py
- training/xtime/datasets/_harth.py
- training/xtime/datasets/_madeline.py
- training/xtime/datasets/_ozone_level_detection_one_hour.py
- training/xtime/datasets/_wisdm.py
- training/xtime/datasets/dataset.py
NA
Adding new method to `DatasetPrerequisites` class that checks if `tsfresh` library is installed. Refactoring datasets to use this new method.
> Checking  if `tsfresh` library is installed.

- training/poetry.lock
NA
Updating `poetry.lock` file (this should have been done with the previous commit).
NA
> Updating `poetry.lock` file.

- training/README.md
NA
- Fixing bugs in example commands.
- Splitting prerequisites section into multiple subsections.
- Adding info on how to use this project as a dependency.
NA
> Updating readme file.

- training/README.md
- training/notebooks/datasets/churn_modelling.ipynb
- training/notebooks/datasets/eye_movements.ipynb
- training/notebooks/datasets/forest_cover_type.ipynb
- training/notebooks/datasets/gas_concentrations.ipynb
- training/notebooks/datasets/gesture_phase.ipynb
- training/notebooks/datasets/rossmann_store_sales.ipynb
- training/notebooks/datasets/telco_customer_churn.ipynb
- training/notebooks/datasets/year_prediction_msd.ipynb
NA
Fixing bugs in multiple notebooks.
- Some of them are typos (e.g., use of train split instead of validation).
- Others are related to code refactor at some point in time, and Jupyter notebooks were not updated.
> Fixing bugs in Jupyter notebooks.

- training/README.md
NA
Some example commands in the README file did not work (they were supported by previous versions of `xtime.training`). This commit fixes it.
NA
> Fixing bugs in README file.

- training/xtime/estimators/estimator.py
NA
These additional key-value arguments are now passed to Estimator._evaluate_classifier only, and can include the following:
- `predict_proba_kwargs` (dict): key-value arguments to pass to `model.predict_proba` methods, can be useful to, e.g., limit number of trees.
> Adding support for kwargs in `Estimator.evaluate` method.

- training/xtime/main.py
- training/xtime/stages/search_hp.py
NA
The fit parameters are `kwargs` parameters in `Estimator.fit_model` methods. Previously, they were not exposed via python or command line interface API. This commit adds `--fit-params` command line argument that can be used to provide estimator-specific parameters (these parameters are passed to underlying `model.fit` method). One usage example is to provide `early_stopping_rounds` for XGBoost models. The specification format is the same as string format for hyperparameter, e.g.:
```
--fit-params="params:early_stopping_rounds=4000"
```
> Adding support for fit parameters (`--fit-params`).

- training/tests/contrib/test_mlflow_ext.py
- training/xtime/contrib/mlflow_ext.py
NA
Parsable strings are `run_id`, `mlflow:run_id`, `mlflow:/run_id` and `mlflow:///run_id`.
> New function that parses a string and returns MLflow run ID.

- training/xtime/contrib/xgboost_ext.py
NA
New parameters include `num_trees` (number of trees to use to compute model statistics) and `cache` (for faster computations when this function needs to be called multiple times).
> New parameters for the `get_model_stats` function.

- training/xtime/datasets/dataset.py
- training/xtime/main.py
NA
This command now accepts two parameters - `--verbose` that instructs to output detailed information about datasets, and `--format` that specifies output format (json / yaml / pretty).
> Updating `dataset describe` command.

- training/tests/estimators/test_model_loader.py
- training/xtime/contrib/sklearn_ext.py
- training/xtime/contrib/xgboost_ext.py
- training/xtime/estimators/estimator.py
NA
This commit updates the `Model` class that provides unified API to load tree-based and other models in current XTIME implementation. It will be considered legacy format once XTIME adopts MLflow ML model logging feature. This commit adds a feature to load LightGBM models. It also introduces a number of unit tests.
> Unified model loading for `legacy` serialziation format.

- training/xtime/estimators/estimator.py
NA
This commit updates the train callback (TrainCallback) to write additional file - `model_info.yaml` that contains ML model metadata. This simplifies subsequent model loading (even though model loading was possible before). The train callback becomes an object responsible for writing metadata for a train run. It logs information about run itself, datasets, model and test results. File names are unified too (run_info.yaml, data_info.yaml, model_info.yaml and test_info.yaml). Future commits can introduce a new class (that will probably replace the `Model` class) that will be used in pair with train callback, but to load experiment metadata, as well as ML models in a unified way.
> Adding model info file.

- training/README.md
- training/poetry.lock
- training/pyproject.toml
- training/tests/test_cli.py
- training/tests/test_registry.py
- training/xtime/estimators/_rapids.py
- training/xtime/estimators/estimator.py
NA
This commit adds a new estimator (`rapids-rf`) that trains a random forest model using RAPIDS from NVIDIA. New optional dependencies (`rapids-12`) installs necessary libraries what currently works only for CUDA 12 and Python 3.9.
>  RAPIDS: GPU-accelerated random forest model.

- training/xtime/contrib/tune_ext.py
NA
- New optional `skip_model_stats (boolean)` parameter to skip computing model descriptive statistics (such as max depth and others). Is used on NOX tests.
- Fixing bug related to accessing invalid `key` in MLflow run tags. This is probably due to updates in other parts of the code base that changed tags. The `problem` tag was replaced with `dataset_name` and `dataset_version` tags.
- Removing old code that used manual mapping to identify model file name based on model name. This code is replaced by the new `LegacySavedModelInfo` class.
> `Analysis.get_trial_stats` - new features and bug fixes.

- training/noxfile.py
NA
This commit adds new `model_search_hp_test` NOX test for three models (xgboost, catboost and lightgbm). This test tests hyperparameter search run, and validates its outputs.
> Nox test for testing `search_hp` stage.

- .github/pull_request_template.md
NA
- Extended set of comit types (unit tests, refactoring, etc.).
- More detailed guidelines on how to use this template.
> Pull Request template updates.

- training/poetry.lock
- training/pyproject.toml
NA
This commit updates dev dependencies. Transient dependencies could also be updated.
> Updating dev dependencies to latest versions.

- training/noxfile.py
NA
This commit adds new `lint` session (`nox -s lint`) that runs ruff's linter (`ruff check`).
> New nox session for code linting (`lint`) with ruff.

- training/pyproject.toml
NA
See the title. This is for Poetry's dynamic versioning plugin.
> Changing version format from SemVer to PEP440.

- training/xtime/estimators/estimator.py
Latest versions of Ray removed `_get_session` making `get_session` available instead. This fix checks if these methods exist and uses the one that exists (`_get_session` first, then `get_session`). If none of these methods exist for some reason, placeholder function is used that returns None.
- [x ] Bug fix.
Select all that apply, and delete the others. If these changes are for `xtime.training`, please make sure to
provide unit tests and/or nox tests for bug fixes and new features.
> Fix for _get_session does not exist.

- training/xtime/estimators/estimator.py
NA
This PR fixes a "bug" that was resulting in PR curve looking differently on different machines. This was due to using scikit-learn's `PrecisionRecallDisplay` class that internally (starting some version) updates passed matplotlib's axes. So different versions of scikit-learn resulted in different charts. This commit removes dependency on that class and plots PR by itself.
Select one of these options, and delete the others.
Select all that apply, and delete the others. If these changes are for `xtime.training`, please make sure to
provide unit tests and/or nox tests for bug fixes and new features.
> PR curve looks different on different systems.

- training/tests/datasets/test_dataset.py
- training/xtime/datasets/dataset.py
The `Dataset.save` method not checks for certain files which already present and can impact subsequent data loading calls. If such files found, and overwrite is set to False, exception is raised. This commit also fixes the bug when a metadata file is always overwritten, but split files are only overwritten when they do not already present.
> Correct dataset serialization.

- .vscode/settings.json
NA
Adding VSCode settings file.
NA
> VSCode settings.

- training/xtime/datasets/_telco_customer_churn.py
- training/xtime/errors.py
- training/xtime/estimators/estimator.py
- training/xtime/hparams/recommender.py
- training/xtime/stages/search_hp.py
NA
Fixing various typos across multiple files.
> Fixing various typos.
